<?xml version="1.0" encoding="utf-8"?><Database Name="Lmis_UserManagement" Class="UserManagementDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=evolution.ge;Initial Catalog=Lmis_UserManagement;Persist Security Info=True;User ID=sa" SettingsObjectName="CITI.EVO.UserManagement.DAL.Properties.Settings" SettingsPropertyName="Lmis_UserManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UM_AttributeCategories" Member="UM_AttributeCategories">
    <Type Name="UM_AttributeCategory">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProjectID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_AttributeCategory_UM_AttributesSchemaNode" Member="AttributesSchemaNodes" Storage="_UM_AttributesSchemaNodes" ThisKey="ID" OtherKey="AttributeCategoryID" Type="UM_AttributesSchemaNode" />
      <Association Name="UM_Project_UM_AttributeCategory" Member="Project" ThisKey="ProjectID" OtherKey="ID" Type="UM_Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UM_Users" Member="UM_Users">
    <Type Name="UM_User">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoginName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="IsSuperAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UserCategoryID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PasswordExpirationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_User_UM_GroupUser" Member="GroupUsers" Storage="_UM_GroupUsers" ThisKey="ID" OtherKey="UserID" Type="UM_GroupUser" />
      <Association Name="UM_User_UM_LoginToken" Member="LoginTokens" ThisKey="ID" OtherKey="UserID" Type="UM_LoginToken" />
      <Association Name="UM_User_UM_MessageViewer" Member="MessageViewers" ThisKey="ID" OtherKey="UserID" Type="UM_MessageViewer" />
      <Association Name="UM_User_UM_UserAttribute" Member="UserAttributes" Storage="_UM_UserAttributes" ThisKey="ID" OtherKey="UserID" Type="UM_UserAttribute" />
      <Association Name="UM_User_UM_UserLog" Member="UserLogs" ThisKey="ID" OtherKey="UserID" Type="UM_UserLog" />
      <Association Name="UM_UserCategory_UM_User" Member="UserCategory" ThisKey="UserCategoryID" OtherKey="ID" Type="UM_UserCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UM_AttributesSchemaNodes" Member="UM_AttributesSchemaNodes">
    <Type Name="UM_AttributesSchemaNode">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AttributeCategoryID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AttributeTypeID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AttributesSchemaID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_AttributesSchemaNode_UM_GroupAttribute" Member="GroupAttributes" Storage="_UM_GroupAttributes" ThisKey="ID" OtherKey="AttributesSchemaNodeID" Type="UM_GroupAttribute" />
      <Association Name="UM_AttributesSchemaNode_UM_RuleAttribute" Member="RuleAttributes" Storage="_UM_RuleAttributes" ThisKey="ID" OtherKey="AttributesSchemaNodeID" Type="UM_RuleAttribute" />
      <Association Name="UM_AttributesSchemaNode_UM_UserAttribute" Member="UserAttributes" ThisKey="ID" OtherKey="AttributesSchemaNodeID" Type="UM_UserAttribute" />
      <Association Name="UM_AttributeCategory_UM_AttributesSchemaNode" Member="AttributeCategory" ThisKey="AttributeCategoryID" OtherKey="ID" Type="UM_AttributeCategory" IsForeignKey="true" />
      <Association Name="UM_AttributesSchema_UM_AttributesSchemaNode" Member="AttributesSchema" ThisKey="AttributesSchemaID" OtherKey="ID" Type="UM_AttributesSchema" IsForeignKey="true" />
      <Association Name="UM_AttributeType_UM_AttributesSchemaNode" Member="AttributeType" ThisKey="AttributeTypeID" OtherKey="ID" Type="UM_AttributeType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UM_AttributesSchemas" Member="UM_AttributesSchemas">
    <Type Name="UM_AttributesSchema">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProjectID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_AttributesSchema_UM_AttributesSchemaNode" Member="AttributesSchemaNodes" Storage="_UM_AttributesSchemaNodes" ThisKey="ID" OtherKey="AttributesSchemaID" Type="UM_AttributesSchemaNode" />
      <Association Name="UM_Project_UM_AttributesSchema" Member="Project" ThisKey="ProjectID" OtherKey="ID" Type="UM_Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UM_AttributeTypes" Member="UM_AttributeTypes">
    <Type Name="UM_AttributeType">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProjectID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_AttributeType_UM_AttributesSchemaNode" Member="UM_AttributesSchemaNodes" ThisKey="ID" OtherKey="AttributeTypeID" Type="UM_AttributesSchemaNode" />
      <Association Name="UM_Project_UM_AttributeType" Member="Project" ThisKey="ProjectID" OtherKey="ID" Type="UM_Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UM_GroupAttributes" Member="UM_GroupAttributes">
    <Type Name="UM_GroupAttribute">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AttributesSchemaNodeID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_AttributesSchemaNode_UM_GroupAttribute" Member="AttributesSchemaNode" ThisKey="AttributesSchemaNodeID" OtherKey="ID" Type="UM_AttributesSchemaNode" IsForeignKey="true" />
      <Association Name="UM_Group_UM_GroupAttribute" Member="Group" Storage="_UM_Group" ThisKey="GroupID" OtherKey="ID" Type="UM_Group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UM_GroupOrganizations" Member="UM_GroupOrganizations">
    <Type Name="UM_GroupOrganization">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OrganizationID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="UM_Group_UM_GroupOrganization" Member="UM_Group" ThisKey="GroupID" OtherKey="ID" Type="UM_Group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UM_Groups" Member="UM_Groups">
    <Type Name="UM_Group">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ProjectID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_Group_UM_GroupAttribute" Member="GroupAttributes" Storage="_UM_GroupAttributes" ThisKey="ID" OtherKey="GroupID" Type="UM_GroupAttribute" />
      <Association Name="UM_Group_UM_GroupOrganization" Member="UM_GroupOrganizations" ThisKey="ID" OtherKey="GroupID" Type="UM_GroupOrganization" />
      <Association Name="UM_Group_UM_Group" Member="Children" ThisKey="ID" OtherKey="ParentID" Type="UM_Group" />
      <Association Name="UM_Group_UM_GroupUser" Member="GroupUsers" Storage="_UM_GroupUsers" ThisKey="ID" OtherKey="GroupID" Type="UM_GroupUser" />
      <Association Name="UM_Group_UM_Permission" Member="Permissions" Storage="_UM_Permissions" ThisKey="ID" OtherKey="GroupID" Type="UM_Permission" />
      <Association Name="UM_Group_UM_Group" Member="Parent" ThisKey="ParentID" OtherKey="ID" Type="UM_Group" IsForeignKey="true" />
      <Association Name="UM_Project_UM_Group" Member="Project" Storage="_UM_Project" ThisKey="ProjectID" OtherKey="ID" Type="UM_Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UM_GroupUsers" Member="UM_GroupUsers">
    <Type Name="UM_GroupUser">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AccessLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_Group_UM_GroupUser" Member="Group" ThisKey="GroupID" OtherKey="ID" Type="UM_Group" IsForeignKey="true" />
      <Association Name="UM_User_UM_GroupUser" Member="User" ThisKey="UserID" OtherKey="ID" Type="UM_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UM_LoginTokens" Member="UM_LoginTokens">
    <Type Name="UM_LoginToken">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoginToken" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ExpireDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastAccessDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeleteReason" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_User_UM_LoginToken" Member="User" ThisKey="UserID" OtherKey="ID" Type="UM_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UM_Messages" Member="UM_Messages">
    <Type Name="UM_Message">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ObjectID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_Message_UM_MessageViewer" Member="MessageViewers" ThisKey="ID" OtherKey="MessageID" Type="UM_MessageViewer" />
    </Type>
  </Table>
  <Table Name="dbo.UM_MessageViewer" Member="UM_MessageViewers">
    <Type Name="UM_MessageViewer">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MessageID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_Message_UM_MessageViewer" Member="Message" ThisKey="MessageID" OtherKey="ID" Type="UM_Message" IsForeignKey="true" />
      <Association Name="UM_User_UM_MessageViewer" Member="User" ThisKey="UserID" OtherKey="ID" Type="UM_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UM_PermissionParameters" Member="UM_PermissionParameters">
    <Type Name="UM_PermissionParameter">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PermissionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_Permission_UM_PermissionParameter" Member="Permission" ThisKey="PermissionID" OtherKey="ID" Type="UM_Permission" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UM_Permissions" Member="UM_Permissions">
    <Type Name="UM_Permission">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ResourceID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RuleValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_Permission_UM_PermissionParameter" Member="PermissionParameters" ThisKey="ID" OtherKey="PermissionID" Type="UM_PermissionParameter" />
      <Association Name="UM_Group_UM_Permission" Member="Group" ThisKey="GroupID" OtherKey="ID" Type="UM_Group" IsForeignKey="true" />
      <Association Name="UM_Resource_UM_Permission" Member="Resource" ThisKey="ResourceID" OtherKey="ID" Type="UM_Resource" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UM_Projects" Member="UM_Projects">
    <Type Name="UM_Project">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_Project_UM_AttributeCategory" Member="AttributeCategories" Storage="_UM_AttributeCategories" ThisKey="ID" OtherKey="ProjectID" Type="UM_AttributeCategory" />
      <Association Name="UM_Project_UM_AttributesSchema" Member="AttributesSchemas" Storage="_UM_AttributesSchemas" ThisKey="ID" OtherKey="ProjectID" Type="UM_AttributesSchema" />
      <Association Name="UM_Project_UM_AttributeType" Member="AttributeTypes" Storage="_UM_AttributeTypes" ThisKey="ID" OtherKey="ProjectID" Type="UM_AttributeType" />
      <Association Name="UM_Project_UM_Group" Member="Groups" Storage="_UM_Groups" ThisKey="ID" OtherKey="ProjectID" Type="UM_Group" />
      <Association Name="UM_Project_UM_Resource" Member="Resources" Storage="_UM_Resources" ThisKey="ID" OtherKey="ProjectID" Type="UM_Resource" />
      <Association Name="UM_Project_UM_Rule" Member="Rules" Storage="_UM_Rules" ThisKey="ID" OtherKey="ProjectID" Type="UM_Rule" />
      <Association Name="UM_Project_UM_UserLog" Member="UserLogs" Storage="_UM_UserLogs" ThisKey="ID" OtherKey="ProjectID" Type="UM_UserLog" />
    </Type>
  </Table>
  <Table Name="dbo.UM_Resources" Member="UM_Resources">
    <Type Name="UM_Resource">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ProjectID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_Resource_UM_Permission" Member="UM_Permissions" ThisKey="ID" OtherKey="ResourceID" Type="UM_Permission" />
      <Association Name="UM_Resource_UM_Resource" Member="Children" ThisKey="ID" OtherKey="ParentID" Type="UM_Resource" />
      <Association Name="UM_Project_UM_Resource" Member="Project" ThisKey="ProjectID" OtherKey="ID" Type="UM_Project" IsForeignKey="true" />
      <Association Name="UM_Resource_UM_Resource" Member="Parent" ThisKey="ParentID" OtherKey="ID" Type="UM_Resource" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UM_RuleAttributes" Member="UM_RuleAttributes">
    <Type Name="UM_RuleAttribute">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RuleID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AttributesSchemaNodeID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_AttributesSchemaNode_UM_RuleAttribute" Member="AttributesSchemaNode" ThisKey="AttributesSchemaNodeID" OtherKey="ID" Type="UM_AttributesSchemaNode" IsForeignKey="true" />
      <Association Name="UM_Rule_UM_RuleAttribute" Member="Rule" ThisKey="RuleID" OtherKey="ID" Type="UM_Rule" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UM_Rules" Member="UM_Rules">
    <Type Name="UM_Rule">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProjectID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CanView" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanAdd" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanEdit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_Rule_UM_RuleAttribute" Member="RuleAttributes" Storage="_UM_RuleAttributes" ThisKey="ID" OtherKey="RuleID" Type="UM_RuleAttribute" />
      <Association Name="UM_Project_UM_Rule" Member="Project" ThisKey="ProjectID" OtherKey="ID" Type="UM_Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UM_UserAttributes" Member="UM_UserAttributes">
    <Type Name="UM_UserAttribute">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AttributesSchemaNodeID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_AttributesSchemaNode_UM_UserAttribute" Member="AttributesSchemaNode" ThisKey="AttributesSchemaNodeID" OtherKey="ID" Type="UM_AttributesSchemaNode" IsForeignKey="true" />
      <Association Name="UM_User_UM_UserAttribute" Member="User" ThisKey="UserID" OtherKey="ID" Type="UM_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UM_UserCategories" Member="UM_UserCategories">
    <Type Name="UM_UserCategory">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_UserCategory_UM_User" Member="Users" ThisKey="ID" OtherKey="UserCategoryID" Type="UM_User" />
    </Type>
  </Table>
  <Table Name="dbo.UM_UserLog" Member="UM_UserLogs">
    <Type Name="UM_UserLog">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ProjectID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IPaddress" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hashcode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="UM_Project_UM_UserLog" Member="Project" Storage="_UM_Project" ThisKey="ProjectID" OtherKey="ID" Type="UM_Project" IsForeignKey="true" />
      <Association Name="UM_User_UM_UserLog" Member="User" ThisKey="UserID" OtherKey="ID" Type="UM_User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>